# Generated by Django 3.2.8 on 2021-10-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0002_alter_taty_taty_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taty',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
